### ISSUE TITLE
Replace block destruction mcfunction command with fillBlocks API command.

### ISSUE THREAD

**Issue by jessejohn01** [laynebritton/jl-fast-treecapitator#10]
This is required to resolve the bug in issue #5. This will also be faster overall.

**Comment by jessejohn01** [comment]
- [ ] Create a mapping of blocks to their item counterparts.
- [ ] Spawn items for every log destroyed with spawn items API calls.
- [ ] Stretch goal: Take a look at seeing the item the player is currently holding and see if it is enchanted. We can then mimic fortune functionality based on the enchantment.

**Comment by laynebritton** [comment]
Related to https://github.com/laynebritton/jl-fast-treecapitator/issues/48

**Comment by jessejohn01** [comment]
Completed in #49
