### ISSUE TITLE
update addon to newest version of minecraft

### ISSUE THREAD

**Issue by TheWeaknd** [laynebritton/jl-fast-treecapitator#18]
can you update the addon to the newest version of minecraft? cause the addon no longer work at version 1.20
i hope u will update it soon, thank u

**Comment by laynebritton** [comment]
Hi @TheWeaknd 

Thanks for bringing this to our attention. We'll take a look and get an update out soon for 1.20

**Comment by jessejohn01** [comment]
@laynebritton Lol just as I commented they released 1.3.0-beta.1.20.0-stable.

**Comment by jessejohn01** [comment]
A pull request has been opened and can be tracked at #20.

**Comment by jessejohn01** [comment]
This is complete and merged.

**Comment by laynebritton** [comment]
Hi @TheWeaknd , a new release has been published with Minecraft 1.20 support. Thanks again for bringing this to our attention 😎 And ty to @jessejohn01 for getting this update out in record time 🤠

**Comment by laynebritton** [comment]
Hi @TheWeaknd . We've been considering adding customization on which blocks from the base game can and can not be vein-mined. 

Two questions for you:
1. Which other blocks from the base game of Minecraft would you like to be breakable with vein-mining? 

2. Could you post a link to one of the addons you're using that has custom blocks you would like to see be breakable with JL-Fast-Treecapitator? It would be helpful for us to see how other developers have implemented their custom blocks.

**Comment by TheWeaknd** [comment]
hi @laynebritton, here is the link of the addon
