### ISSUE TITLE
Leaf destruction algorithm when destroying trees

### ISSUE THREAD

**Issue by laynebritton** [laynebritton/jl-fast-treecapitator#2]
When destroying a tree I expect:

- The logs will be mined and destroyed.
- Some or all of the leaves will be mined and destroyed.

Currently only the logs will be mined, the leaves are untouched.

Workarounds: Leaves in Minecraft naturally decay overtime, so given enough time the leaves will disappear on their own.

**Comment by laynebritton** [comment]
@jessejohn01 do we still want to implement this? imo this might be unnecessary, but open to arguments for it

**Comment by jessejohn01** [comment]
@laynebritton I am fine dropping it off. I like that the leaves are left behind and naturally decay but that's just my opinion.

**Comment by laynebritton** [comment]
@jessejohn01 cool dropping this for now. Will re-open if a need is displayed.
