### ISSUE TITLE
Addon not working with minecraft version 1.20.10

### ISSUE THREAD

**Issue by TheWeaknd** [laynebritton/jl-fast-treecapitator#22]
due to minecraft update, the addon no longer work!
hope you will fix it soon
thank you

**Comment by laynebritton** [comment]
Hi @TheWeaknd ,

Thanks for letting us know the latest update has broken functionality. I'll take a look into updating this weekend.

**Comment by laynebritton** [comment]
Hey @TheWeaknd 

A fix has been released for compatibility with Minecraft 1.20.10

Thanks again for letting us know! 🤠 

Also, in our spare time we've been thinking through support for adding custom block support to this mod, which you mentioned here https://github.com/laynebritton/jl-fast-treecapitator/issues/18#issuecomment-1584621599  We're somewhat limited by what Microsoft allows us to do using the Minecraft behavior pack typescript API, but it is on our radar! 🔍

**Comment by TheWeaknd** [comment]
Hi @laynebritton 
I really appreciate all the work you have done!
And thanks for check out my suggestion

**Comment by laynebritton** [comment]
Hi @TheWeaknd 

We're excited to announce support for adding custom blocks to the JL Fast Treecapitator mod.

You can add any block with a `blockid` in Minecraft to JL Fast Treecapitator now. As long as the custom blocks added by other creators have a block id, this mod should be able to handle vein-mining them

In a single player world a user, or an operator on a server, can use the command `>jltree add block:id` where `block:id` is the block of the custom block.

https://github.com/laynebritton/jl-fast-treecapitator#-configuration

Thank you for the suggestion of this feature!

Best,
Layne
