### ISSUE TITLE
Turn on or off command for veinminer

### ISSUE THREAD

**Issue by TheWeaknd** [laynebritton/jl-fast-treecapitator#25]
can you add a feature that can turn on-off the veinminer? i have break all the house for accident. Is it possible to add a command about it?

**Comment by laynebritton** [comment]
Hey @TheWeaknd ,

oh no I’m sorry to hear that accident occurred. 

We are currently developing and testing a command interface for configuration. This is a great suggestion to include, I’ll make sure to include it in our road map. 

Thank you for bringing this to our attention. When this new version is released I’ll ping this issue.

Layne

**Comment by laynebritton** [comment]
Hi @TheWeaknd 

We just released a new version of jl-fast-treecapitator that introduces user configuration.

On the latest version, you can toggle on-off the mod by using
`>jltree toggle`

See here for more info, or use `>jltree help` in-game
![image](https://github.com/laynebritton/jl-fast-treecapitator/assets/21363865/03449d1e-ecf0-49d5-accd-3b22149a86e7)

**Comment by laynebritton** [comment]
Issue discovered with user config on multiplayer servers. Issue reopened until resolved

**Comment by laynebritton** [comment]
Hi @TheWeaknd 

We're excited to announce that configuration of JL Fast Treecapitator is available in-game now.

If you're playing in single-player or are an op on your server, you can use the command `>jltree toggle` to toggle the mod on and off.

Learn more in the project's readme here: https://github.com/laynebritton/jl-fast-treecapitator#-configuration

Thank you for opening this issue to let us know this would be a useful addition!

Layne
