### ISSUE TITLE
[Update] Minecraft v1.20.30

### ISSUE THREAD

**Issue by TheWeaknd** [laynebritton/jl-fast-treecapitator#27]
And the addon break in the new version
Thank youu

**Comment by laynebritton** [comment]
Hey @TheWeaknd , thank you for reporting this. I’ll take a look soon

**Comment by jessejohn01** [comment]
@laynebritton This is most likely due to blockbreakevent being renamed to playerblockbreakevent.

**Comment by jessejohn01** [comment]
#28 has been opened to resolve this.
