### ISSUE TITLE
Enchantment Compabiltiy

### ISSUE THREAD

**Issue by TheWeaknd** [laynebritton/jl-fast-treecapitator#48]
Can you make this add-on work with 'Fortune', 'Silk Touch'? If possible, it gonna be great!

**Comment by laynebritton** [comment]
Hi @TheWeaknd,

Thanks for bringing this to our attention. It's been on our radar for a bit, but I'll keep this open for an official feature request.

Thanks!

**Comment by laynebritton** [comment]
Hello @TheWeaknd ,

@jessejohn01 and I just published version 2.0 of JL Treecap. This update includes support for applying enchantments from tools to the output of the vein mining.

The latest version is available under our releases page: https://github.com/laynebritton/jl-fast-treecapitator/releases

Thanks for the suggestion, glad you're enjoying using JL Treecap!
Layne
