### ISSUE TITLE
Handle exceptions more gracefully

### ISSUE THREAD

**Issue by jessejohn01** [laynebritton/jl-fast-treecapitator#6]
Should we run into an error, we shouldn't down a server. If we run into an error just attempt to log the error and continue forward with vanilla gameplay.

**Comment by laynebritton** [comment]
@jessejohn01 is there anything built in for error handling? Is a try/catch block sufficient to handle this for now?

**Comment by jessejohn01** [comment]
https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/beforewatchdogterminateeventsignal
This event is fired before the server terminates from an error. We could subscribe to this event and attempt to handle any exceptions that we recognize. At least log them as well.

**Comment by laynebritton** [comment]
Fixed with Version 2.0
