### ISSUE TITLE
Redstone missing from block list

### ISSUE THREAD

**Issue by laynebritton** [laynebritton/jl-fast-treecapitator#7]
Add Redstone ore to the auto miner list

**Comment by laynebritton** [comment]
When mined, redstone ore blocks change to a new block with a new id, lit_redstone_ore

We should resolve in the work done for https://github.com/laynebritton/jl-fast-treecapitator/issues/8 - Add lit_redstone_ore to the map of mineable blocks for redstone ore

**Comment by jessejohn01** [comment]
Did they change the redstone ore id in the API?

**Comment by laynebritton** [comment]
@jessejohn01 see https://github.com/laynebritton/jl-fast-treecapitator/pull/11

**Comment by laynebritton** [comment]
This has been completed in: https://github.com/laynebritton/jl-fast-treecapitator/pull/11

Resolved
