### ISSUE TITLE
Regular ore vs. deepslate ore

### ISSUE THREAD

**Issue by GlowBrick** [laynebritton/jl-fast-treecapitator#8]
Crouch mining regular ore does not proc deepslate ore when adjacent.

**Comment by laynebritton** [comment]
@GlowBrick ty for reporting this 😎 

@jessejohn01 thoughts on approaching this? Should we group the deepslate ores with non-deepslate? Maybe each viable vein block has an associated map of blocks that can be auto mined alongside it.

**Comment by jessejohn01** [comment]
In Minecraft they are considered separate ore. We would have to make multiple groupings of ore and maintain our own list of groupings and what can be mined together. Could probably call them families of ore. E.g. The iron ore family.

**Comment by laynebritton** [comment]
This has been completed in: https://github.com/laynebritton/jl-fast-treecapitator/pull/11

Resolved
