### ISSUE TITLE
Update API calls to use Vector3 instead of deprecated BlockLocations.

### ISSUE THREAD

**Issue by jessejohn01** [laynebritton/jl-fast-treecapitator#9]
The Bedrock API changed to using Vector3s instead of BlockLocations for any x,y,z coordinates.

**Comment by laynebritton** [comment]
@jessejohn01 Agreed, we should migrate to stay up to date with the API

**Comment by jessejohn01** [comment]
This issue is currently blocked. There is a bug with dimension.getBlock that doesn't grab blocks correctly.

**Comment by jessejohn01** [comment]
I jumped the gun. Vector3 is not implemented yet. It is in preview builds of Minecraft currently and I have the code ready for when that goes live.

**Comment by jessejohn01** [comment]
This was completed under PR #16
